### ISSUE TITLE
Where is the definition of "golang-build-env" ?

### ISSUE THREAD

**Issue by luamintw** [batect/batect-sample-golang#113]
when I run command "./batect setup" and an error occurs "The container 'golang-build-env' referenced by task 'setup' does not exist.". 
So where is the definition of "golang-build-env" ?

**Comment by charleskorn** [comment]
Hi @luamintw, thanks for the question. The `golang-build-env` container is defined in `golang-bundle`'s [`batect-bundle.yml`](https://github.com/batect/golang-bundle/blob/448f1e68fd9ef65d12efdb7512cf6e014b93f793/batect-bundle.yml#L2), which is included into this project's `batect.yml` [here](https://github.com/batect/batect-sample-golang/blob/8db0f132a5f58844d49fe0bb81d794fc6a6dda95/batect.yml#L91).

Have you made any changes to the configuration by any chance?

**Comment by luamintw** [comment]
Thanks @charleskorn , I remarked the include part. hhhh
